name: tomopy_pydantic_galaxy
channels:
  - astra-toolbox
  - bioconda
  - conda-forge
  - defaults
  - file:///nfs/chess/sw/miniconda3_msnc/envs/build_msnctools/conda-bld
dependencies:
  - astra-toolbox==2.1.2
  - bioblend==1.0.0
  - ephemeris==0.10.7
  - h5py==3.6.0
  - lmfit==1.0.3
  - matplotlib==3.5.2
  - msnctools=2023.1.*
  - nexpy==0.13.3
  - pip==22.3.1
  - pydantic==1.10.2
  - python==3.9.13
  - tomopy==1.12.2
  - xarray==2022.11.0
# Optional
#  - jupyter
  - jupyterlab==3.5.0
#  - spyder
