name: tomopy-galaxy
channels:
  - astra-toolbox
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - astra-toolbox==2.0.0
  - bioblend==0.16.0
  - ephemeris==0.10.7
  - pip==21.3.1
  - python==3.9.5
  - tomopy==1.11.0
  - pip:
    - pyinputplus==0.2.12
    - h5py==3.6.0
  - jupyter==1.0.0 # Not strictly necessary, just provided for users' convenience.
  - spyder==5.2.2  # Not strictly necessary, just provided for users' convenience.
