name: tomopy-spyder
channels:
  - astra-toolbox
  - conda-forge
  - defaults
dependencies:
  - astra-toolbox==2.0.0
  - pip==21.3.1
  - python==3.9.5
  - tomopy==1.11.0
  - spyder==5.2.2
  - pip:
    - pyinputplus==0.2.12
    - h5py==3.6.0
